# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\programs\projects\python3\Python3_Learning\src\OCR_Result_Manage\OCRDataBase\MainForm.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(714, 531)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comboBox_picTypes = QtGui.QComboBox(self.centralWidget)
        self.comboBox_picTypes.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_picTypes.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox_picTypes.setObjectName(_fromUtf8("comboBox_picTypes"))
        self.horizontalLayout_5.addWidget(self.comboBox_picTypes)
        self.pushButton_Refresh_PicTypes = QtGui.QPushButton(self.centralWidget)
        self.pushButton_Refresh_PicTypes.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_Refresh_PicTypes.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_Refresh_PicTypes.setStyleSheet(_fromUtf8("border-image: url(:/my_pic/Resources/刷新.png);"))
        self.pushButton_Refresh_PicTypes.setText(_fromUtf8(""))
        self.pushButton_Refresh_PicTypes.setObjectName(_fromUtf8("pushButton_Refresh_PicTypes"))
        self.horizontalLayout_5.addWidget(self.pushButton_Refresh_PicTypes)
        self.pushButton_Choose_PicTypes = QtGui.QPushButton(self.centralWidget)
        self.pushButton_Choose_PicTypes.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_Choose_PicTypes.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_Choose_PicTypes.setStyleSheet(_fromUtf8("border-image: url(:/my_pic/Resources/选择.png);"))
        self.pushButton_Choose_PicTypes.setText(_fromUtf8(""))
        self.pushButton_Choose_PicTypes.setObjectName(_fromUtf8("pushButton_Choose_PicTypes"))
        self.horizontalLayout_5.addWidget(self.pushButton_Choose_PicTypes)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tableWidget_Records = QtGui.QTableWidget(self.centralWidget)
        self.tableWidget_Records.setAutoFillBackground(True)
        self.tableWidget_Records.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Records.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_Records.setObjectName(_fromUtf8("tableWidget_Records"))
        self.tableWidget_Records.setColumnCount(0)
        self.tableWidget_Records.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_Records)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_LoadRecords = QtGui.QPushButton(self.centralWidget)
        self.pushButton_LoadRecords.setObjectName(_fromUtf8("pushButton_LoadRecords"))
        self.horizontalLayout_3.addWidget(self.pushButton_LoadRecords)
        self.pushButton_ShowRecordContent = QtGui.QPushButton(self.centralWidget)
        self.pushButton_ShowRecordContent.setObjectName(_fromUtf8("pushButton_ShowRecordContent"))
        self.horizontalLayout_3.addWidget(self.pushButton_ShowRecordContent)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(147, 375))
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setStyleSheet(_fromUtf8("font: 75 9pt \"Adobe Arabic\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.graphicsView_OriginalPic = QtGui.QGraphicsView(self.dockWidgetContents)
        self.graphicsView_OriginalPic.setObjectName(_fromUtf8("graphicsView_OriginalPic"))
        self.verticalLayout.addWidget(self.graphicsView_OriginalPic)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setStyleSheet(_fromUtf8("font: 75 9pt \"Adobe Arabic\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.label_PictureName = QtGui.QLabel(self.dockWidgetContents)
        self.label_PictureName.setStyleSheet(_fromUtf8("font: 9pt \"宋体\";"))
        self.label_PictureName.setText(_fromUtf8(""))
        self.label_PictureName.setObjectName(_fromUtf8("label_PictureName"))
        self.horizontalLayout.addWidget(self.label_PictureName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setStyleSheet(_fromUtf8("font: 75 9pt \"Adobe Arabic\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.pushButton_update_ocrtext = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_update_ocrtext.setObjectName(_fromUtf8("pushButton_update_ocrtext"))
        self.horizontalLayout_6.addWidget(self.pushButton_update_ocrtext)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.textBrowser_OCRResult = QtGui.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_OCRResult.setMaximumSize(QtCore.QSize(2000, 60))
        self.textBrowser_OCRResult.setReadOnly(False)
        self.textBrowser_OCRResult.setObjectName(_fromUtf8("textBrowser_OCRResult"))
        self.verticalLayout.addWidget(self.textBrowser_OCRResult)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setStyleSheet(_fromUtf8("font: 75 9pt \"Adobe Arabic\";"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.pushButton_update_realtext = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_update_realtext.setObjectName(_fromUtf8("pushButton_update_realtext"))
        self.horizontalLayout_7.addWidget(self.pushButton_update_realtext)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.textBrowser_realtext = QtGui.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_realtext.setMaximumSize(QtCore.QSize(2000, 60))
        self.textBrowser_realtext.setReadOnly(False)
        self.textBrowser_realtext.setObjectName(_fromUtf8("textBrowser_realtext"))
        self.verticalLayout.addWidget(self.textBrowser_realtext)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setStyleSheet(_fromUtf8("font: 75 11pt \"Adobe Arabic\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_TimeConsume = QtGui.QLabel(self.dockWidgetContents)
        self.label_TimeConsume.setStyleSheet(_fromUtf8("font: 75 12pt \"Times New Roman\";"))
        self.label_TimeConsume.setText(_fromUtf8(""))
        self.label_TimeConsume.setObjectName(_fromUtf8("label_TimeConsume"))
        self.horizontalLayout_2.addWidget(self.label_TimeConsume)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 714, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindow.setMenuBar(self.menuBar)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.listWidget_log = QtGui.QListWidget(self.dockWidgetContents_2)
        self.listWidget_log.setObjectName(_fromUtf8("listWidget_log"))
        self.horizontalLayout_4.addWidget(self.listWidget_log)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
        self.action_import_pic_into_db = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/my_pic/Resources/库存上报.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_import_pic_into_db.setIcon(icon)
        self.action_import_pic_into_db.setObjectName(_fromUtf8("action_import_pic_into_db"))
        self.action_import_record_into_db = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/my_pic/Resources/手动上传.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_import_record_into_db.setIcon(icon1)
        self.action_import_record_into_db.setObjectName(_fromUtf8("action_import_record_into_db"))
        self.action_quit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/my_pic/Resources/错误.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_quit.setIcon(icon2)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_import_real_text = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/my_pic/Resources/上传.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_import_real_text.setIcon(icon3)
        self.action_import_real_text.setObjectName(_fromUtf8("action_import_real_text"))
        self.action_import_original_pic_into_db = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/my_pic/Resources/upload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_import_original_pic_into_db.setIcon(icon4)
        self.action_import_original_pic_into_db.setObjectName(_fromUtf8("action_import_original_pic_into_db"))
        self.menu.addAction(self.action_import_pic_into_db)
        self.menu.addAction(self.action_import_original_pic_into_db)
        self.menu.addAction(self.action_import_record_into_db)
        self.menu.addSeparator()
        self.menu.addAction(self.action_import_real_text)
        self.menu_2.addAction(self.action_quit)
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_6.setText(_translate("MainWindow", "图片筛选", None))
        self.tableWidget_Records.setSortingEnabled(True)
        self.pushButton_LoadRecords.setText(_translate("MainWindow", "加载记录", None))
        self.pushButton_ShowRecordContent.setText(_translate("MainWindow", "显示该记录", None))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "记录内容详细显示", None))
        self.label.setText(_translate("MainWindow", "检测图片", None))
        self.label_4.setText(_translate("MainWindow", "图片名称：", None))
        self.label_2.setText(_translate("MainWindow", "算法识别", None))
        self.pushButton_update_ocrtext.setText(_translate("MainWindow", "更新", None))
        self.label_5.setText(_translate("MainWindow", "人工识别", None))
        self.pushButton_update_realtext.setText(_translate("MainWindow", "更新", None))
        self.label_3.setText(_translate("MainWindow", "耗    时：", None))
        self.menu.setTitle(_translate("MainWindow", "数据处理", None))
        self.menu_2.setTitle(_translate("MainWindow", "文件", None))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "日志记录", None))
        self.action_import_pic_into_db.setText(_translate("MainWindow", "导入图片到数据库", None))
        self.action_import_record_into_db.setText(_translate("MainWindow", "导入OCR检测记录到数据库", None))
        self.action_quit.setText(_translate("MainWindow", "退出", None))
        self.action_import_real_text.setText(_translate("MainWindow", "导入人工识别数据", None))
        self.action_import_original_pic_into_db.setText(_translate("MainWindow", "导入原始图片到数据库", None))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

